import { Link } from '@tanstack/react-router';
import { Container, Eyebrow, Heading, Section } from '@kka/site-ui';
import type { PracticeArea, SiteBootstrap } from '../types';
import { PracticeCard } from '../components/PracticeCard';
import { LeadForm } from '../components/LeadForm';
import { PageHero } from './AboutPage';
import { SafeImage } from '../components/SafeImage';
import { Seo } from '../components/Seo';
export function PracticeAreasPage({data}:{data:SiteBootstrap}){return <><Seo settings={data.settings} title="Areas of Practice" description="Explore the legal services offered by Kariuki Kagunda & Co. Advocates."/><PageHero eyebrow="Areas of Practice" title="LEGAL SOLUTIONS BUILT AROUND REAL-WORLD NEEDS." copy="From personal injury and employment disputes to property, intellectual property and digital business, our work combines legal rigor with practical execution."/><Section><Container><div className="practice-index-grid">{data.practiceAreas.map(a=><PracticeCard area={a} key={a.id}/>)}</div></Container></Section><Section tone="dark"><Container className="split-cta"><div><Eyebrow>Not sure where your matter fits?</Eyebrow><Heading>TELL US WHAT HAPPENED.</Heading><p>You do not need to diagnose the legal category before contacting us. Give us the essential facts and our team can route the enquiry appropriately.</p></div><div className="dark-form"><LeadForm areas={data.practiceAreas} compact/></div></Container></Section></>}
export function PracticeDetailPage({area,data}:{area:PracticeArea;data:SiteBootstrap}){const related=data.partners.filter(p=>p.practiceAreas.includes(area.slug));return <><Seo settings={data.settings} title={area.title} description={area.summary}/><PageHero eyebrow="Area of Practice" title={area.title.toUpperCase()} copy={area.summary}/><Section><Container className="detail-two-col"><article className="prose"><Eyebrow>How We Help</Eyebrow><Heading>{area.title}</Heading><p>{area.description}</p><h2>Services</h2><ul>{area.services.map(x=><li key={x}>{x}</li>)}</ul>{area.faqs.length>0&&<><h2>Frequently Asked Questions</h2>{area.faqs.map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</>}</article><aside className="detail-aside"><Eyebrow>Talk to the Firm</Eyebrow><LeadForm areas={data.practiceAreas} compact/></aside></Container></Section>{related.length>0&&<Section tone="ivory"><Container><Eyebrow>Relevant Professionals</Eyebrow><Heading>PEOPLE WHO CAN HELP.</Heading><div className="mini-partners">{related.map((p,i)=><Link to="/team/$slug" params={{slug:p.slug}} key={p.id}><SafeImage asset={p.image} fallback={i===1?'/assets/partner-wanjiru.png':'/assets/partner-kariuki.png'} alt={p.name}/><span><b>{p.name}</b><small>{p.title}</small></span></Link>)}</div></Container></Section>}</>}
