import { Container, Eyebrow, Heading, Section } from '@kka/site-ui';
import type { Partner, SiteBootstrap } from '../types';
import { PartnerCard } from '../components/PartnerCard';
import { LeadForm } from '../components/LeadForm';
import { PageHero } from './AboutPage';
import { Link } from '@tanstack/react-router';
import { SafeImage } from '../components/SafeImage';
import { Seo } from '../components/Seo';
export function TeamPage({data}:{data:SiteBootstrap}){return <><Seo settings={data.settings} title="Our Team" description="Meet the professionals behind Kariuki Kagunda & Co. Advocates."/><PageHero eyebrow="Our Team" title="THE PEOPLE BEHIND THE COUNSEL." copy="Our public team profiles put the people responsible for client service at the centre of the firm’s digital experience."/><Section><Container><div className="partner-grid-large">{data.partners.map(p=><PartnerCard partner={p} variant="featured" key={p.id}/>)}</div></Container></Section><Section tone="dark"><Container className="team-manifesto"><Eyebrow>How We Work</Eyebrow><Heading>LEGAL WORK IS A TEAM SPORT WITH INDIVIDUAL ACCOUNTABILITY.</Heading><div><p>Each instruction should have clear ownership, active supervision and a transparent next action. The public site reflects the people; the LawFirm OS provides the machinery behind their work.</p></div></Container></Section></>}
export function PartnerPage({partner,data}:{partner:Partner;data:SiteBootstrap}){const areas=data.practiceAreas.filter(a=>partner.practiceAreas.includes(a.slug));const posts=data.publications.filter(p=>p.author?.id===partner.id||p.practiceAreas.some(x=>partner.practiceAreas.includes(x)));const fallback=partner.slug.includes('wanjiru')?'/assets/partner-wanjiru.png':'/assets/partner-kariuki.png';return <><Seo settings={data.settings} title={`${partner.name} | ${partner.title}`} description={partner.summary} image={partner.image?.url}/><section className="partner-hero"><Container className="partner-hero-grid"><div className="partner-hero-copy"><Eyebrow>{partner.title}</Eyebrow><Heading as="h1">{partner.name.toUpperCase()}</Heading><p>{partner.summary}</p><div className="partner-contact-links">{partner.email&&<a href={`mailto:${partner.email}`}>{partner.email}</a>}{partner.phone&&<a href={`tel:${partner.phone}`}>{partner.phone}</a>}</div></div><div className="partner-portrait"><SafeImage asset={partner.image} fallback={fallback} alt={`${partner.name}, ${partner.title}`}/></div></Container></section><Section><Container className="detail-two-col"><article className="prose"><Eyebrow>Profile</Eyebrow><Heading>CLIENT-FIRST. PRACTICAL. PREPARED.</Heading><p>{partner.bio}</p>{areas.length>0&&<><h2>Practice Areas</h2><div className="tag-links">{areas.map(a=><Link to="/practice-areas/$slug" params={{slug:a.slug}} key={a.id}>{a.title}</Link>)}</div></>} {partner.credentials.length>0&&<><h2>Credentials</h2><ul>{partner.credentials.map(x=><li key={x}>{x}</li>)}</ul></>} {partner.memberships.length>0&&<><h2>Professional Memberships</h2><ul>{partner.memberships.map(x=><li key={x}>{x}</li>)}</ul></>} {partner.education.length>0&&<><h2>Education</h2><ul>{partner.education.map(x=><li key={x}>{x}</li>)}</ul></>}</article><aside className="detail-aside"><Eyebrow>Start a Conversation</Eyebrow><LeadForm areas={data.practiceAreas} compact/></aside></Container></Section>{posts.length>0&&<Section tone="ivory"><Container><Eyebrow>Insights</Eyebrow><Heading>RELATED READING.</Heading><div className="article-grid">{posts.slice(0,6).map(p=><Link className="article-card" key={p.id} to="/insights/$slug" params={{slug:p.slug}}><SafeImage asset={p.cover} fallback="/assets/media-ip.png" alt={p.title}/><div><small>{p.kind}</small><h3>{p.title}</h3><p>{p.excerpt}</p><span>Read →</span></div></Link>)}</div></Container></Section>}</>}
