import React, { useEffect, useState } from 'react';
import { Loader2, Megaphone, RotateCcw } from 'lucide-react';
import { websiteApi } from '../../lib/websiteApi';

export const WebsitePublishingPanel: React.FC = () => {
  const [releases, setReleases] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = () => { setLoading(true); websiteApi.releases().then(setReleases).catch((cause: any) => setError(cause?.message || String(cause))).finally(() => setLoading(false)); };
  useEffect(() => { load(); const timer = setInterval(load, 5000); return () => clearInterval(timer); }, []);
  async function publish() { setLoading(true); setError(''); try { await websiteApi.publish(); setTimeout(load, 900); } catch (cause: any) { setError(cause?.message || String(cause)); setLoading(false); } }
  async function rollback(version: number) { if (!confirm(`Restore release ${version}? A new release will be generated from that snapshot.`)) return; setLoading(true); try { await websiteApi.rollback(version); setTimeout(load, 900); } catch (cause: any) { setError(cause?.message || String(cause)); setLoading(false); } }
  const published = releases.find(release => release.status === 'PUBLISHED'); const latest = releases[0];
  return <section className="admin-card overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-4 sm:p-5 dark:border-slate-800"><div><h2 className="text-lg font-semibold">Publishing</h2><p className="mt-1 text-xs text-slate-500">Review readiness, publish an audited release, or restore a previous release.</p></div><button type="button" className="admin-btn-primary min-h-11" onClick={publish} disabled={loading}><Megaphone className="h-4 w-4" /> Publish website</button></header><div className="grid gap-3 p-4 sm:grid-cols-3"><Readiness label="Current public release" value={published ? `Release ${published.version}` : 'No release'} /><Readiness label="Latest operation" value={latest ? latest.status.replaceAll('_', ' ') : 'Not started'} /><Readiness label="Routes in release" value={published?.manifest?.routeCount ?? '—'} /></div>{error && <div className="mx-4 mb-4 rounded-lg bg-rose-50 p-3 text-xs text-rose-700 dark:bg-rose-950/20 dark:text-rose-300" role="alert">{error}</div>}{loading && !releases.length ? <div className="grid min-h-40 place-items-center"><Loader2 className="h-5 w-5 animate-spin text-amber-500" /></div> : <div className="p-4 pt-0"><div className="hidden grid-cols-[auto_minmax(120px,1fr)_minmax(150px,1fr)_auto] gap-4 border-b border-slate-200 px-3 py-3 text-xs font-semibold text-slate-500 md:grid dark:border-slate-800"><span>Release</span><span>Status</span><span>Published</span><span>Action</span></div><div className="space-y-2">{releases.map((release, index) => <div key={release.id} className="grid gap-2 rounded-xl border border-slate-200 p-3 md:grid-cols-[auto_minmax(120px,1fr)_minmax(150px,1fr)_auto] md:items-center dark:border-slate-800"><strong>Release {release.version}</strong><div>{release.error && <p className="mb-1 text-xs text-rose-600">{release.error}</p>}<span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] dark:bg-slate-800">{release.status}</span></div><span className="text-xs text-slate-500">{release.publishedAt ? new Date(release.publishedAt).toLocaleString() : 'Not published'}</span>{release.status === 'PUBLISHED' && index > 0 ? <button type="button" className="min-h-11 text-left text-xs text-amber-700 md:text-right" onClick={() => rollback(release.version)}><RotateCcw className="mr-1 inline h-3.5 w-3.5" />Restore</button> : <span />}</div>)}{!releases.length && <div className="rounded-xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500 dark:border-slate-700">No release history is available.</div>}</div></div>}</section>;
};
function Readiness({ label, value }: { label: string; value: React.ReactNode }) { return <div className="rounded-xl border border-slate-200 p-3 dark:border-slate-800"><span className="block text-[10px] uppercase tracking-wide text-slate-500">{label}</span><strong className="mt-1 block text-sm">{value}</strong></div>; }
