import { Award, Gavel, Play, ShieldCheck, Users } from 'lucide-react';
import { Container, Eyebrow, Heading, Section } from '@kka/site-ui';
import { Link } from '@tanstack/react-router';
import type { SiteBootstrap } from '../types';
import { PartnerCard } from './PartnerCard';
import { PracticeCard } from './PracticeCard';
import { TestimonialCarousel } from './TestimonialCarousel';
import { LeadForm } from './LeadForm';
import { SafeImage } from './SafeImage';
const metricIcons=[Users,Gavel,ShieldCheck,Award];
export function Hero(){return <section className="hero"><div className="hero-noise"/><div className="hero-art"><img src="/assets/hero-justice.png" alt="Lady Justice sculpture"/></div><Container className="hero-layout"><div className="hero-copy"><Eyebrow>Kariuki Kagunda & Co. Advocates</Eyebrow><Heading as="h1">A LAW FIRM THAT<br/>FIGHTS FOR <span>JUSTICE</span></Heading><p>A dedicated law firm committed to protecting your rights and delivering justice.</p><div className="hero-actions"><Link to="/contact" className="ui-button ui-button-gold"><span>Contact Us</span><span>→</span></Link><a href="#media" className="watch-link"><i><Play size={15} fill="currentColor"/></i>Watch Our Video</a></div><div className="hero-values"><div><b>INTEGRITY</b><span>Our Foundation</span></div><div><b>EXCELLENCE</b><span>Our Standard</span></div><div><b>JUSTICE</b><span>Our Purpose</span></div></div></div><blockquote>“Justice<br/>is not an option.<br/>It is a duty.”</blockquote></Container><a href="#who-we-are" className="hero-scroll">SCROLL <span>↓</span></a></section>}
export function WhoWeAre({data}:{data:SiteBootstrap}){return <Section id="who-we-are" className="who"><Container><Eyebrow>Who We Are</Eyebrow><div className="who-grid"><div className="who-copy"><Heading>WE ARE A <span>LEADING LAW FIRM</span><br/>IN KENYA WHICH OFFERS PRACTICAL AND PROFESSIONAL LEGAL SERVICES</Heading><p>Kariuki Kagunda & Co. Advocates is a full-service law firm in Kenya committed to providing practical, innovative and result-oriented legal solutions to individuals, businesses and organisations.</p><ul><li>Practical legal services.</li><li>Expert service and experience.</li><li>Flexibility in legal solutions.</li><li>Innovative legal support.</li></ul><Link className="ui-button ui-button-outline" to="/about"><span>Know About Us</span><span>→</span></Link></div><div className="partner-pair">{data.partners.slice(0,2).map(p=><PartnerCard partner={p} key={p.id} variant="featured"/>)}</div><aside className="who-aside">Experienced.<br/>Trusted.<br/>Results Driven.<i/></aside></div></Container></Section>}
export function Metrics({data}:{data:SiteBootstrap}){return <section className="metrics"><Container className="metrics-grid">{data.metrics.map((m,i)=>{const I=metricIcons[i%metricIcons.length] ?? Award;return <div key={m.id}><I/><strong>{m.value}</strong><span>{m.label}</span></div>})}</Container></section>}
export function Services({data}:{data:SiteBootstrap}){return <Section className="services"><Container><div className="section-split-head"><div><Eyebrow>Our Services</Eyebrow><Heading>COMPREHENSIVE LEGAL<br/>SOLUTIONS FOR ALL YOUR NEEDS</Heading></div><div><p>We provide strategic legal counsel across a broad range of practice areas, helping our clients navigate complex legal challenges with confidence.</p><Link className="ui-button ui-button-outline" to="/practice-areas"><span>View All Services</span><span>→</span></Link></div></div><div className="practice-grid">{data.practiceAreas.slice(0,5).map(a=><PracticeCard area={a} key={a.id}/>)}</div></Container></Section>}
export function MediaInsights({data}:{data:SiteBootstrap}){const [feature,...rest]=data.publications;return <section id="media" className="media-section"><Container className="media-layout"><div className="media-copy"><Eyebrow>In the Media</Eyebrow><Heading>LEGAL INSIGHTS<br/>& UPDATES</Heading><p>Keep up with our latest insights, articles and thought leadership on matters that impact you.</p><Link className="ui-button ui-button-gold" to="/insights"><span>View All Media</span><span>→</span></Link></div>{feature&&<Link to="/insights/$slug" params={{slug:feature.slug}} className="featured-media"><SafeImage asset={feature.cover} fallback="/assets/media-feature.png" alt={feature.title}/><span className="featured-play" aria-hidden><Play fill="currentColor"/></span><div><strong>{feature.title}</strong><span>{feature.duration||'Read'}</span></div></Link>}<div className="media-list">{rest.slice(0,2).map((p,i)=><Link to="/insights/$slug" params={{slug:p.slug}} key={p.id}><SafeImage asset={p.cover} fallback={i?'/assets/media-employment.png':'/assets/media-ip.png'} alt={p.title}/><div><small>{new Date(p.publishedAt).toLocaleDateString('en-KE',{day:'numeric',month:'short',year:'numeric'})}</small><h3>{p.title}</h3><span>{p.kind==='VIDEO'?'Watch':'Read Article'} →</span></div></Link>)}</div></Container></section>}
export function TeamPreview({data}:{data:SiteBootstrap}){return <Section className="team-preview"><Container className="team-layout"><div><Eyebrow>Our Team</Eyebrow><Heading>MEET THE TEAM</Heading><p>A team of dedicated professionals committed to achieving the best outcomes for our clients.</p><Link className="ui-button ui-button-outline" to="/team"><span>View Our Team</span><span>→</span></Link></div><div className="team-pair">{data.partners.slice(0,2).map(p=><PartnerCard partner={p} key={p.id} variant="compact"/>)}</div><blockquote>“A strong team<br/>builds stronger<br/>futures.”</blockquote></Container></Section>}
export function Testimonials({data}:{data:SiteBootstrap}){return <Section className="testimonials"><Container><div className="testimonial-heading"><div><Eyebrow>Testimonials</Eyebrow><Heading>SEE WHAT OUR CLIENTS<br/>SAY ABOUT US</Heading></div></div><TestimonialCarousel items={data.testimonials}/></Container></Section>}
export function Consultation({data}:{data:SiteBootstrap}){return <Section className="consultation"><Container className="consultation-layout"><div className="consult-photo"><img src="/assets/consultation-partner.png" alt="A legal professional at Kariuki Kagunda & Co. Advocates"/></div><div className="consult-form"><Eyebrow>Let's Talk</Eyebrow><Heading>Let’s Start a<br/>Conversation!</Heading><p>What can we help you with?</p><LeadForm areas={data.practiceAreas} compact/></div><div className="consult-statement"><span>Your<br/>Legal Partner<br/>for a Brighter<br/>Tomorrow.</span><i/></div></Container></Section>}
