import { Award, Gavel, Play, ShieldCheck, Users } from 'lucide-react';
import { Container, Eyebrow, Heading, Section } from '@kka/site-ui';
import { Link } from '@tanstack/react-router';
import type { SiteBootstrap } from '../types';
import { PartnerCard } from './PartnerCard';
import { PracticeCard } from './PracticeCard';
import { TestimonialCarousel } from './TestimonialCarousel';
import { LeadForm } from './LeadForm';
import { SafeImage } from './SafeImage';
type Props={data:SiteBootstrap;content?:Record<string,any>};
const metricIcons=[Users,Gavel,ShieldCheck,Award];
export function Hero({content:c={}}:{content?:Record<string,any>}){return <section className="hero"><div className="hero-noise"/><div className="hero-art"><img src={c.asset?.url||c.imageUrl||'/assets/hero-justice.png'} alt={c.asset?.alt||'Lady Justice sculpture'} fetchPriority="high"/></div><Container className="hero-layout"><div className="hero-copy"><Eyebrow>{c.eyebrow}</Eyebrow><Heading as="h1">{String(c.title||'').split('\n').map((line,i)=><span className="hero-line" key={i}>{line}</span>)}</Heading><p>{c.description}</p><div className="hero-actions"><a href={c.ctaUrl||'/contact'} className="ui-button ui-button-gold"><span>{c.ctaLabel||'Contact Us'}</span><span>&rarr;</span></a>{c.videoUrl&&<a href={c.videoUrl} className="watch-link"><i><Play size={15}/></i>{c.videoLabel||'Watch Our Video'}</a>}</div><div className="hero-values">{(c.values||[]).map((v:any,i:number)=><div key={i}><b>{v.title}</b><span>{v.description}</span></div>)}</div></div>{c.quote&&<blockquote>{c.quote}</blockquote>}</Container><a href="#who-we-are" className="hero-scroll">SCROLL <span>&rarr;</span></a></section>}
export function WhoWeAre({data,content:c={}}:Props){return <Section id="who-we-are" className="who"><Container><Eyebrow>{c.eyebrow}</Eyebrow><div className="who-grid"><div className="who-copy"><Heading>{c.title}</Heading><p>{c.description}</p><ul>{(c.bullets||[]).map((text:string)=><li key={text}>{text}</li>)}</ul><Link className="ui-button ui-button-outline" to="/about"><span>Know About Us</span><span>→</span></Link></div><div className="partner-pair">{(c.slugs?.length?data.partners.filter(p=>c.slugs.includes(p.slug)):data.partners).slice(0,2).map(p=><PartnerCard partner={p} key={p.id} variant="featured"/>)}</div><aside className="who-aside">{c.statement}<i/></aside></div></Container></Section>}
export function Metrics({data,content:c={}}:Props){return <section className="metrics"><Container className="metrics-grid">{data.metrics.map((m,i)=>{const I=metricIcons[i%metricIcons.length] ?? Award;return <div key={m.id}><I/><strong>{m.value}</strong><span>{m.label}</span></div>})}</Container></section>}
export function Services({data,content:c={}}:Props){return <Section className="services"><Container><div className="section-split-head"><div><Eyebrow>{c.eyebrow}</Eyebrow><Heading>{c.title}</Heading></div><div><p>{c.description}</p><Link className="ui-button ui-button-outline" to="/practice-areas"><span>View All Services</span><span>→</span></Link></div></div><div className="practice-grid">{data.practiceAreas.slice(0,5).map(a=><PracticeCard area={a} key={a.id}/>)}</div></Container></Section>}
export function MediaInsights({data,content:c={}}:Props){const feature=data.publications.find(p=>p.slug===c.featuredSlug)||data.publications.find(p=>p.kind==='VIDEO'&&p.videoUrl)||data.publications[0];const rest=data.publications.filter(p=>p.id!==feature?.id);return <section id="media" className="media-section"><Container className="media-layout"><div className="media-copy"><Eyebrow>{c.eyebrow}</Eyebrow><Heading>{c.title}</Heading><p>{c.description}</p><Link className="ui-button ui-button-gold" to="/insights"><span>View All Media</span><span>→</span></Link></div>{feature&&<Link to="/insights/$slug" params={{slug:feature.slug}} className="featured-media"><SafeImage asset={feature.cover} fallback="/assets/media-feature.png" alt={feature.title}/>{feature.kind==='VIDEO'&&feature.videoUrl&&<span className="featured-play" aria-hidden><Play fill="currentColor"/></span>}<div><strong>{feature.title}</strong><span>{feature.duration||'Read'}</span></div></Link>}<div className="media-list">{rest.slice(0,2).map((p,i)=><Link to="/insights/$slug" params={{slug:p.slug}} key={p.id}><SafeImage asset={p.cover} fallback={i?'/assets/media-employment.png':'/assets/media-ip.png'} alt={p.title}/><div><small>{new Date(p.publishedAt).toLocaleDateString('en-KE',{day:'numeric',month:'short',year:'numeric'})}</small><h3>{p.title}</h3><span>{p.kind==='VIDEO'?'Watch':'Read Article'} →</span></div></Link>)}</div></Container></section>}
export function TeamPreview({data,content:c={}}:Props){return <Section className="team-preview"><Container className="team-layout"><div><Eyebrow>{c.eyebrow}</Eyebrow><Heading>{c.title}</Heading><p>{c.description}</p><Link className="ui-button ui-button-outline" to="/team"><span>View Our Team</span><span>→</span></Link></div><div className="team-pair">{(c.slugs?.length?data.partners.filter(p=>c.slugs.includes(p.slug)):data.partners).slice(0,2).map(p=><PartnerCard partner={p} key={p.id} variant="compact"/>)}</div><blockquote>“A strong team<br/>builds stronger<br/>futures.”</blockquote></Container></Section>}
export function Testimonials({data,content:c={}}:Props){return <Section className="testimonials"><Container><div className="testimonial-heading"><div><Eyebrow>{c.eyebrow}</Eyebrow><Heading>{c.title}</Heading></div></div><TestimonialCarousel items={data.testimonials}/></Container></Section>}
export function Consultation({data,content:c={}}:Props){return <Section className="consultation"><Container className="consultation-layout"><div className="consult-photo"><SafeImage asset={c.asset} fallback="/assets/consultation-partner.png" alt={c.asset?.alt||"A legal professional at the firm"}/></div><div className="consult-form"><Eyebrow>{c.eyebrow}</Eyebrow><Heading>Let’s Start a<br/>Conversation!</Heading><p>{c.description}</p><LeadForm areas={data.practiceAreas} definition={data.forms?.find(f=>f.key==='general-enquiry')} compact/></div><div className="consult-statement"><span>{c.statement}</span><i/></div></Container></Section>}

export function PartnerLeadership({data,content:c={}}:Props){return <section className="partner-leadership"><Container><Eyebrow>{c.eyebrow}</Eyebrow><Heading>{c.title}</Heading><p>{c.description}</p><div className="partner-pair">{data.partners.filter(p=>!c.slugs?.length||c.slugs.includes(p.slug)).slice(0,2).map(p=><PartnerCard key={p.id} partner={p} variant="featured"/>)}</div><blockquote>{c.quote}</blockquote></Container></section>}
