import { useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Button, Field, Input, Select, Textarea } from '@kka/site-ui';
import type { PracticeArea } from '../types';
import { submitLead } from '../lib/api';
const schema=z.object({name:z.string().min(2),email:z.string().email().optional().or(z.literal('')),phone:z.string().min(7),practiceAreaSlug:z.string().optional(),message:z.string().min(10),consent:z.boolean().pipe(z.literal(true))});
type Form=z.input<typeof schema>;
function utm(){const p=new URLSearchParams(location.search);return Object.fromEntries(['utm_source','utm_medium','utm_campaign','utm_term','utm_content'].map(k=>[k,p.get(k)||'']).filter(([,v])=>v))}
export function LeadForm({areas,compact=false}:{areas:PracticeArea[];compact?:boolean}){const {register,handleSubmit,reset,formState:{errors,isSubmitting}}=useForm<Form>({defaultValues:{consent:false}});const [result,setResult]=useState<{reference:string}|null>(null);const [failure,setFailure]=useState('');const attribution=useMemo(utm,[]);const submit=async(raw:Form)=>{setFailure('');const parsed=schema.safeParse(raw);if(!parsed.success){setFailure('Please review the highlighted information.');return}try{const r=await submitLead({...parsed.data,source:document.referrer||'DIRECT',landingPage:location.pathname,utm:attribution});setResult(r);reset({consent:false})}catch(e){setFailure(e instanceof Error?e.message:'We could not submit your enquiry. Please try again.')}};if(result)return <div className="lead-success" role="status"><span>Enquiry received</span><h3>Thank you. We’ll take it from here.</h3><p>Your reference is <strong>{result.reference}</strong>. A member of the firm can now review and assign your enquiry in the LawFirm OS.</p><button onClick={()=>setResult(null)}>Send another enquiry</button></div>;return <form className={`lead-form ${compact?'compact':''}`} onSubmit={handleSubmit(submit)} noValidate><Field label="Full Name" error={errors.name?.message}><Input autoComplete="name" placeholder="e.g. Simon Laisama" {...register('name',{required:true})}/></Field><div className="form-two"><Field label="Phone" error={errors.phone?.message}><Input autoComplete="tel" placeholder="e.g. 0722 123456" {...register('phone',{required:true})}/></Field><Field label="Email" error={errors.email?.message}><Input type="email" autoComplete="email" placeholder="example@email.com" {...register('email')}/></Field></div><Field label="Area of Interest"><Select {...register('practiceAreaSlug')}><option value="">Choose a practice area</option>{areas.map(a=><option value={a.slug} key={a.id}>{a.title}</option>)}</Select></Field><Field label="Message" error={errors.message?.message}><Textarea rows={compact?4:6} placeholder="Tell us briefly how we can help..." {...register('message',{required:true})}/></Field><label className="consent"><input type="checkbox" {...register('consent',{required:true})}/><span>I consent to the firm using this information to review and respond to my enquiry. Submitting this form does not by itself create an advocate-client relationship.</span></label>{failure&&<div className="form-failure" role="alert">{failure}</div>}<Button type="submit" disabled={isSubmitting}>{isSubmitting?'Submitting…':'Submit Enquiry'}</Button></form>}
