import React, { useEffect, useState } from 'react';
import { apiClient } from '../../lib/api/client';
import { apiUrl } from '../../config/runtime';
import { authApi, type CurrentAuthUser } from '../../lib/api/auth.api';
import { PdfPlacementEditor, type PlacedAsset } from './PdfPlacementEditor';
import { TemplateStudio } from './TemplateStudio';
interface Version { id:string; versionNumber:number; mimeType:string; status:string; checksumSha256:string }
interface DocumentRecord {id:string; title:string; matterId:string; versions:Version[]; currentVersionId?:string}
interface Asset { id:string; displayName:string; active:boolean; versions:Array<{id:string;version:number}> }
interface Operation {id:string;updatedAt:string;kind:string;status:string;error?:string;outputVersionId?:string;outputDocxVersionId?:string;suggestedMarks?:PlacedAsset[];previewUrl?:string}
export function DocumentStudio() {
  const [documents,setDocuments]=useState<DocumentRecord[]>([]),[matters,setMatters]=useState<Array<{id:string;title:string;internalReference:string}>>([]);
  const [assets,setAssets]=useState<Asset[]>([]),[signatures,setSignatures]=useState<Array<{id:string;professionalDisplayName:string;approvalStatus:string;versions:Array<{id:string;version:number;active:boolean}>}>>([]);
  const [user,setUser]=useState<CurrentAuthUser|null>(null),[docId,setDocId]=useState(''),[versionId,setVersionId]=useState(''),[items,setItems]=useState<PlacedAsset[]>([]);
  const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('documents'),[operations,setOperations]=useState<Operation[]>([]);
  const [matterId,setMatterId]=useState(''),[title,setTitle]=useState(''),[docType,setDocType]=useState('Letter'),[file,setFile]=useState<File|null>(null);
  const [asset,setAsset]=useState(''),[password,setPassword]=useState(''),[reason,setReason]=useState('Apply firm artwork'),[preview,setPreview]=useState('');
  const [presets,setPresets]=useState<Array<{id:string;name:string;xPoints:number;yPoints:number;widthPoints:number;heightPoints:number;rotation:number;opacity:number}>>([]),[presetName,setPresetName]=useState('');
  const [approvals,setApprovals]=useState<Array<{id:string;reason:string;status:string}>>([]);
  const document=documents.find(d=>d.id===docId),version=document?.versions.find(v=>v.id===versionId);
  const permits=(p:string)=>!!user?.permissions.includes(p);
  async function load() {
    const u=await authApi.me();setUser(u);
    const [d,m,a,s,p]=await Promise.all([apiClient.get<DocumentRecord[]>('/documents'),apiClient.get<typeof matters>('/matters'),apiClient.get<Asset[]>('/marks'),u.permissions.includes('document.sign')?apiClient.get<typeof signatures>('/marks/signature-options'):Promise.resolve([]),apiClient.get<typeof presets>('/marks/placements')]);
    setDocuments(d);setMatters(m);setAssets(a);setSignatures(s);setPresets(p);
    if(docId)setOperations(await apiClient.get<Operation[]>('/document-operations',{params:{documentId:docId}}));
  }
  useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
  useEffect(()=>{setItems([]);setPreview('');if(docId)apiClient.get<Operation[]>('/document-operations',{params:{documentId:docId}}).then(setOperations).catch(e=>setMessage(e.message));},[docId]);
  useEffect(()=>{if(!docId)return;const timer=window.setInterval(()=>{apiClient.get<Operation[]>('/document-operations',{params:{documentId:docId}}).then(rows=>{setOperations(rows);if(rows.some(r=>r.status==='COMPLETED'))apiClient.get<DocumentRecord[]>('/documents').then(setDocuments).catch(()=>{});}).catch(()=>{});},4000);return()=>clearInterval(timer);},[docId]);
  useEffect(()=>()=>{if(preview.startsWith('blob:'))URL.revokeObjectURL(preview);},[preview]);
  async function run(fn:()=>Promise<unknown>) {setBusy(true);setMessage('');try{await fn();await load();}catch(e){setMessage(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);setPassword('');}}
  async function createDocument(){const doc=await apiClient.post<DocumentRecord>('/documents',{matterId,title,documentType:docType,category:'Correspondence',confidentialityLevel:'STANDARD'});setDocId(doc.id);setTitle('');if(file){const f=new FormData();f.append('file',file);await apiClient.post(`/documents/${doc.id}/versions`,f);}setTitle('');setFile(null);setMessage('Document saved.');}
  function payload(){return {documentId:docId,inputVersionId:versionId,idempotencyKey:crypto.randomUUID(),items,reason};}
  async function confirmMarks(){let elevationToken:string|undefined;if(password)elevationToken=(await authApi.elevate(password)).elevationToken;const result=await apiClient.post<Operation>('/document-operations/apply',{...payload(),elevationToken});setMessage(`Application ${result.status.toLowerCase().replaceAll('_',' ')}${result.error?`: ${result.error}`:''}`);if(result.outputVersionId){setVersionId(result.outputVersionId);setItems([]);}}
  async function previewMarks(){const blob=await apiClient.post<Blob>('/document-operations/preview',payload(),{responseType:'blob'});setPreview(URL.createObjectURL(blob));}
  return <div className="p-3 sm:p-6 space-y-5 max-w-7xl mx-auto"><h1 className="text-2xl font-serif font-bold">Documents & firm execution</h1><p>Stored matter documents, controlled artwork, and versioned templates.</p>
    <div className="flex flex-wrap gap-2"><button className="admin-btn-secondary" onClick={()=>setTab('documents')}>Documents</button><button className="admin-btn-secondary" onClick={()=>setTab('templates')}>Templates</button><button className="admin-btn-secondary" onClick={()=>run(load)}>Refresh</button></div>
    <p role="status" className="text-sm">{busy?'Working…':message}</p>
    {!user&&<p>Sign in to use stored documents. No document changes are saved offline.</p>}
    {tab==='templates'?<TemplateStudio documentId={docId} canManage={permits('admin.settings_manage')} canGenerate={permits('document.upload')} onMessage={setMessage} />:<>
    <div className="grid lg:grid-cols-[minmax(230px,1fr)_minmax(0,3fr)] gap-5"><aside className="space-y-4"><label className="block">Stored document<select className="admin-input" value={docId} onChange={e=>{const d=documents.find(d=>d.id===e.target.value);setDocId(e.target.value);setVersionId(d?.currentVersionId||d?.versions[0]?.id||'');}}><option value="">Choose document</option>{documents.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label>
      {!documents.length&&<p>No accessible stored documents.</p>}
      {permits('document.upload')&&<form className="admin-card space-y-3" onSubmit={e=>{e.preventDefault();void run(createDocument);}}><h2 className="font-semibold">New document</h2><label>Matter<select className="admin-input" value={matterId} onChange={e=>setMatterId(e.target.value)}><option value="">Choose matter</option>{matters.map(m=><option key={m.id} value={m.id}>{m.internalReference} · {m.title}</option>)}</select></label><label>Title<input className="admin-input" value={title} onChange={e=>setTitle(e.target.value)} /></label><label>Document type<input className="admin-input" value={docType} onChange={e=>setDocType(e.target.value)} /></label><label>Initial file (optional)<input className="w-full" type="file" onChange={e=>setFile(e.target.files?.[0]??null)} /></label><button className="admin-btn-primary" disabled={busy||!matterId||title.trim().length<2}>Create document</button></form>}
    </aside><main className="space-y-4 min-w-0">{document&&<>
      <h2 className="text-xl font-semibold">{document.title}</h2><label>Version<select className="admin-input" value={versionId} onChange={e=>{setVersionId(e.target.value);setItems([]);setPreview('');}}><option value="">Choose version</option>{document.versions.map(v=><option key={v.id} value={v.id}>v{v.versionNumber} · {v.mimeType==='application/pdf'?'PDF':'Editable file'} · {v.status}</option>)}</select></label>
      {version&&<><a className="admin-btn-secondary inline-flex" href={apiUrl(`/documents/versions/${version.id}/download`)}>Download selected version</a><p className="text-xs break-all">SHA-256: {version.checksumSha256}</p></>}
      {permits('document.upload')&&<label className="block">Upload a new version<input type="file" className="block max-w-full" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{const data=new FormData();data.append('file',f);const v=await apiClient.post<Version>(`/documents/${docId}/versions`,data);setVersionId(v.id);setItems([]);});}} /></label>}
      {version?.mimeType==='application/pdf'&&<>
        {permits('document.sign')&&<div className="admin-card space-y-3"><label>Artwork / signature<select className="admin-input" value={asset} onChange={e=>setAsset(e.target.value)}><option value="">Choose an asset version</option>{assets.filter(a=>a.active).flatMap(a=>a.versions.map(v=><option key={v.id} value={`mark:${v.id}`}>{a.displayName} · v{v.version}</option>))}{signatures.filter(s=>s.approvalStatus==='APPROVED').flatMap(s=>s.versions.filter(v=>v.active).map(v=><option key={v.id} value={`signature:${v.id}`}>{s.professionalDisplayName} · signature v{v.version}</option>))}</select></label><button className="admin-btn-secondary" disabled={!asset} onClick={()=>{const[kind,versionId]=asset.split(':');setItems([...items,{kind:kind as 'mark'|'signature',versionId,placement:{page:1,x:40,y:40,width:100,height:60,rotation:0,opacity:1}}]);}}>Add placement</button>
        <label>Saved placement preset<select className="admin-input" defaultValue="" onChange={e=>{const p=presets.find(p=>p.id===e.target.value);if(p&&items.length)setItems(items.map((a,i)=>i===items.length-1?{...a,placement:{...a.placement,x:p.xPoints,y:p.yPoints,width:p.widthPoints,height:p.heightPoints,rotation:p.rotation,opacity:p.opacity}}:a));}}><option value="">Select for last placement</option>{presets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
        {permits('admin.settings_manage')&&<div><input aria-label="Placement preset name" className="admin-input" value={presetName} onChange={e=>setPresetName(e.target.value)} placeholder="Preset name" /><button className="admin-btn-secondary" disabled={!items.length||presetName.length<2||busy} onClick={()=>run(()=>{const p=items[items.length-1].placement;return apiClient.post('/marks/placements',{name:presetName,pageSelection:'EXPLICIT',constraints:{pages:[p.page]},xPoints:p.x,yPoints:p.y,widthPoints:p.width,heightPoints:p.height,rotation:p.rotation,opacity:p.opacity});})}>Save last placement as preset</button></div>}
        </div>}
        <PdfPlacementEditor url={apiUrl(`/documents/versions/${versionId}/download`)} items={items} onChange={setItems} />
        {items.length>0&&<section className="admin-card space-y-3"><label>Reason<input className="admin-input" value={reason} onChange={e=>setReason(e.target.value)} /></label><label>Confirm password for stamps/signatures<input className="admin-input" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} /></label><div className="flex gap-2 flex-wrap"><button className="admin-btn-secondary" disabled={busy} onClick={()=>run(previewMarks)}>Preview rendered PDF</button><button className="admin-btn-primary" disabled={busy||reason.trim().length<2} onClick={()=>run(confirmMarks)}>Apply to new draft</button></div></section>}
        {preview&&<><a href={preview} target="_blank" rel="noreferrer" className="admin-btn-secondary inline-flex">Open rendered preview</a><iframe title="Rendered PDF preview" className="w-full h-96" src={preview} /></>}
      </>}
      <section className="admin-card space-y-2"><h3 className="font-semibold">Generation & application history</h3>{!operations.length&&<p>No operations yet.</p>}{operations.map(o=><div key={o.id} className="border-b border-slate-500/20 py-2"><p>{o.kind} · {o.status}</p>{o.error&&<p role="alert">{o.error}</p>}{o.previewUrl&&<a href={o.previewUrl} target="_blank" rel="noreferrer">Open template preview</a>}{o.outputVersionId&&<button className="admin-btn-secondary" onClick={()=>{setVersionId(o.outputVersionId!);setItems(o.suggestedMarks??[]);}}>Open output{o.suggestedMarks?.length?' and review template marks':''}</button>}{(o.status==='FAILED'||(['PROCESSING','QUEUED'].includes(o.status)&&Date.now()-new Date(o.updatedAt).getTime()>300000))&&<button className="admin-btn-secondary" disabled={busy} onClick={()=>run(async()=>{const elevationToken=password?(await authApi.elevate(password)).elevationToken:undefined;return apiClient.post(o.kind==='GENERATE'?`/document-templates/generations/${o.id}/retry`:`/document-operations/${o.id}/retry`,{elevationToken});})}>Retry</button>}</div>)}</section>
      {permits('approval.decide')&&<section className="admin-card"><button className="admin-btn-secondary" onClick={()=>run(async()=>setApprovals(await apiClient.get<typeof approvals>('/approvals')))}>Load pending approvals</button>{approvals.map(a=><div key={a.id}><p>{a.reason}</p><button className="admin-btn-secondary" onClick={()=>run(()=>apiClient.post(`/approvals/${a.id}/decision`,{decision:'APPROVED'}))}>Approve</button><button className="admin-btn-secondary" onClick={()=>run(()=>apiClient.post(`/approvals/${a.id}/decision`,{decision:'REJECTED'}))}>Reject</button></div>)}</section>}
    </>}</main></div></>}
  </div>;
}
