import React, { useEffect, useState } from 'react';
import { apiClient } from '../../lib/api/client';
import type { PlacedAsset } from './PdfPlacementEditor';
interface Block {type:'heading'|'paragraph'|'table';text:string;rows?:string[][]}
interface TemplateVersion {id:string;version:number;status:string;content?:string;sourceMimeType?:string;mergeSchema?:{configuration?:{logo:string;marks:PlacedAsset[]}}}
interface Template {id:string;key:string;name:string;category:string;active:boolean;versions:TemplateVersion[]}
export function TemplateStudio({documentId,canManage,canGenerate,onMessage}:{documentId:string;canManage:boolean;canGenerate:boolean;onMessage:(s:string)=>void}) {
  const [templates,setTemplates]=useState<Template[]>([]),[selected,setSelected]=useState(''),[versionId,setVersionId]=useState('');
  const [name,setName]=useState(''),[key,setKey]=useState(''),[category,setCategory]=useState('Correspondence');
  const [header,setHeader]=useState('{firm.name}'),[footer,setFooter]=useState('Matter: {matter.reference}'),[blocks,setBlocks]=useState<Block[]>([{type:'heading',text:'{input.subject}'},{type:'paragraph',text:'Dear {input.recipient},'},{type:'paragraph',text:'{input.body}'}]);
  const [recipient,setRecipient]=useState(''),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[logo,setLogo]=useState('active');
  const [file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[format,setFormat]=useState('structured');
  const [marks,setMarks]=useState<PlacedAsset[]>([]),[asset,setAsset]=useState(''),[assets,setAssets]=useState<Array<{id:string;displayName:string;versions:Array<{id:string;version:number}>}>>([]);
  async function load(){setTemplates(await apiClient.get<Template[]>('/document-templates'));setAssets(await apiClient.get<typeof assets>('/marks'));}
  useEffect(()=>{load().catch(e=>onMessage(e.message));},[]);
  async function run(action:()=>Promise<unknown>){setBusy(true);try{await action();await load();}catch(e){onMessage(e instanceof Error?e.message:'Template request failed');}finally{setBusy(false);}}
  function choose(id:string){setSelected(id);const t=templates.find(t=>t.id===id);if(!t){setName('');setKey('');setVersionId('');return;}setName(t.name);setKey(t.key);setCategory(t.category);chooseVersion(t.versions[0]);}
  function chooseVersion(v?:TemplateVersion){setVersionId(v?.id||'');if(v?.content){try{const c=JSON.parse(v.content);setHeader(c.header);setFooter(c.footer);setBlocks(c.blocks);setFormat('structured');}catch{onMessage('This legacy template requires a new structured version.');}}else if(v?.sourceMimeType)setFormat('docx');setLogo(v?.mergeSchema?.configuration?.logo||'active');setMarks(v?.mergeSchema?.configuration?.marks||[]);}
  async function save(){const payload={name,key,category,content:{header,footer,blocks},configuration:{logo,marks}};let id=selected;
    if(!id){const result=await apiClient.post<{templateId:string;id:string}>('/document-templates',payload);id=result.templateId;setSelected(id);setVersionId(result.id);}
    if(format==='docx'){if(!file)throw new Error('Choose a DOCX template');const data=new FormData();data.append('configuration',JSON.stringify({logo,marks}));data.append('file',file);const v=await apiClient.post<{id:string}>(`/document-templates/${id}/docx`,data);setVersionId(v.id);setFile(null);}
    else if(selected){const v=await apiClient.post<{id:string}>(`/document-templates/${id}/versions`,payload);setVersionId(v.id);}
    onMessage('New template version saved as draft.');
  }
  async function generate(preview=false){const result=await apiClient.post<{status:string}>('/document-templates/'+(preview?'preview':'generate'),{documentId,templateVersionId:versionId,idempotencyKey:crypto.randomUUID(),inputs:{'input.recipient':recipient,'input.subject':subject,'input.body':body}});onMessage(`Template ${preview?'preview':'generation'} ${result.status.toLowerCase()}. Follow progress in document history.`);}
  function updateBlock(i:number,patch:Partial<Block>){setBlocks(blocks.map((b,j)=>i===j?{...b,...patch}:b));}
  return <div className="space-y-4"><h2 className="text-xl font-semibold">Document templates</h2><p>Choose a stored document in the Documents tab before generating or previewing a template.</p>
    <div className="grid md:grid-cols-2 gap-3"><label>Template<select className="admin-input" value={selected} onChange={e=>choose(e.target.value)}><option value="">New template</option>{templates.map(t=><option value={t.id} key={t.id}>{t.name}{t.active?'':' · retired'}</option>)}</select></label><label>Version<select className="admin-input" value={versionId} onChange={e=>chooseVersion(templates.find(t=>t.id===selected)?.versions.find(v=>v.id===e.target.value))}><option value="">Choose version</option>{templates.find(t=>t.id===selected)?.versions.map(v=><option value={v.id} key={v.id}>v{v.version} · {v.status} · {v.sourceMimeType?'Word':'In-app'}</option>)}</select></label></div>
    {canManage&&<section className="admin-card space-y-3"><h3 className="font-semibold">Template editor</h3><div className="grid sm:grid-cols-2 gap-3"><label>Name<input className="admin-input" value={name} onChange={e=>setName(e.target.value)} /></label><label>Reference (lowercase letters, digits, hyphens)<input className="admin-input" value={key} disabled={!!selected} onChange={e=>setKey(e.target.value)} /></label><label>Category<input className="admin-input" value={category} onChange={e=>setCategory(e.target.value)} /></label><label>Authoring method<select className="admin-input" value={format} onChange={e=>setFormat(e.target.value)}><option value="structured">In-app editor</option><option value="docx">Word DOCX upload</option></select></label></div>
      <p className="text-sm">Merge fields: {'{firm.name}, {client.name}, {matter.reference}, {matter.title}, {court.name}, {date.today}, {signatory.name}, {input.recipient}, {input.subject}, {input.body}'}. Required fields must have values.</p>
      {format==='docx'?<><p>Use {'{firm.logo}'} in a dedicated Word paragraph for the managed logo. Macros, external links, and embedded objects are not supported.</p><input type="file" aria-label="Word template" accept=".docx" onChange={e=>setFile(e.target.files?.[0]??null)} /></>:<><label>Header<textarea className="admin-input" value={header} onChange={e=>setHeader(e.target.value)} /></label>{blocks.map((b,i)=><div key={i} className="border border-slate-500/20 rounded p-3 space-y-2"><select aria-label={`Block ${i+1} type`} className="admin-input" value={b.type} onChange={e=>updateBlock(i,{type:e.target.value as Block['type'],rows:e.target.value==='table'?[['Column 1','Column 2'],['','']]:undefined})}><option value="heading">Heading</option><option value="paragraph">Paragraph</option><option value="table">Table</option></select>{b.type==='table'?<div className="space-y-2">{b.rows?.map((row,r)=><div key={r} className="flex gap-2">{row.map((cell,c)=><input key={c} aria-label={`Row ${r+1} column ${c+1}`} className="admin-input min-w-0" value={cell} onChange={e=>updateBlock(i,{rows:b.rows!.map((cells,ri)=>ri===r?cells.map((text,ci)=>ci===c?e.target.value:text):cells)})} />)}</div>)}<button className="admin-btn-secondary" onClick={()=>updateBlock(i,{rows:[...(b.rows||[]),Array(b.rows?.[0]?.length||2).fill('')]})}>Add row</button><button className="admin-btn-secondary" onClick={()=>updateBlock(i,{rows:b.rows?.map(row=>[...row,''])})}>Add column</button></div>:<textarea aria-label={`Block ${i+1} text`} className="admin-input" rows={4} value={b.text} onChange={e=>updateBlock(i,{text:e.target.value})} />}<div className="flex gap-2"><button className="admin-btn-secondary" disabled={i===0} onClick={()=>{const next=[...blocks];[next[i-1],next[i]]=[next[i],next[i-1]];setBlocks(next);}}>Move up</button><button className="admin-btn-secondary" disabled={blocks.length===1} onClick={()=>setBlocks(blocks.filter((_,j)=>j!==i))}>Remove block</button></div></div>)}<button className="admin-btn-secondary" onClick={()=>setBlocks([...blocks,{type:'paragraph',text:''}])}>Add block</button><label className="block">Footer<textarea className="admin-input" value={footer} onChange={e=>setFooter(e.target.value)} /></label></>}
      <label>Branding<select className="admin-input" value={logo} onChange={e=>setLogo(e.target.value)}><option value="active">Pin active firm logo at generation</option><option value="none">No logo</option></select></label>
      <label>Suggested document mark<select className="admin-input" value={asset} onChange={e=>setAsset(e.target.value)}><option value="">Choose version</option>{assets.flatMap(a=>a.versions.map(v=><option key={v.id} value={v.id}>{a.displayName} v{v.version}</option>))}</select></label><button className="admin-btn-secondary" disabled={!asset} onClick={()=>setMarks([...marks,{kind:'mark',versionId:asset,placement:{page:1,x:40,y:40,width:100,height:60,rotation:0,opacity:1}}])}>Attach mark placement</button>
      {marks.map((m,i)=><fieldset className="border rounded p-2" key={i}><legend>Suggested mark {i+1}</legend><div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{(['page','x','y','width','height','rotation','opacity'] as const).map(k=><label key={k}>{k}<input className="admin-input" type="number" value={m.placement[k]} step={k==='opacity'?0.1:1} onChange={e=>setMarks(marks.map((a,j)=>j===i?{...a,placement:{...a.placement,[k]:Number(e.target.value)}}:a))} /></label>)}</div><button className="admin-btn-secondary" onClick={()=>setMarks(marks.filter((_,j)=>j!==i))}>Remove suggested mark</button></fieldset>)}
      <p>Suggested stamps are reviewed and applied through the document approval workflow after generation.</p>
      <div className="flex flex-wrap gap-2"><button className="admin-btn-primary" disabled={busy||name.length<2||!key||(format==='docx'&&!file)} onClick={()=>run(save)}>Save new draft version</button><button className="admin-btn-secondary" disabled={busy||!versionId} onClick={()=>run(async()=>{await apiClient.post(`/document-templates/versions/${versionId}/publish`);onMessage('Template published.');})}>Publish version</button><button className="admin-btn-secondary" disabled={busy||!selected} onClick={()=>run(()=>apiClient.patch(`/document-templates/${selected}`,{active:!templates.find(t=>t.id===selected)?.active}))}>Toggle availability</button></div>
    </section>}
    <section className="admin-card space-y-3"><h3 className="font-semibold">Generate for selected document</h3><label>Recipient<input className="admin-input" value={recipient} onChange={e=>setRecipient(e.target.value)} /></label><label>Subject<input className="admin-input" value={subject} onChange={e=>setSubject(e.target.value)} /></label><label>Body<textarea className="admin-input" rows={5} value={body} onChange={e=>setBody(e.target.value)} /></label><div className="flex gap-2">{canManage&&<button className="admin-btn-secondary" disabled={busy||!documentId||!versionId} onClick={()=>run(()=>generate(true))}>Preview template</button>}<button className="admin-btn-primary" disabled={busy||!documentId||!versionId||!canGenerate} onClick={()=>run(()=>generate())}>Generate draft</button></div></section>
  </div>;
}
