import PizZip from 'pizzip';
export function demonstrationDocx() {
  const zip = new PizZip();
  zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');
  zip.file('_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');
  zip.file('word/document.xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+['{firm.logo}','{firm.name}','SYNTHETIC DEMONSTRATION - NOT FOR FILING','Matter: {matter.reference}','{input.subject}','Dear {input.recipient},','{input.body}','{signatory.name}'].map(t=>`<w:p><w:r><w:t>${t}</w:t></w:r></w:p>`).join('')+'<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>');
  return zip.generate({type:'nodebuffer'});
}
export const demonstrationLetter = { header: '{firm.name}', footer: 'SYNTHETIC DEMONSTRATION - NOT FOR FILING', blocks: [{type:'heading' as const,text:'{input.subject}'},{type:'paragraph' as const,text:'Dear {input.recipient},'},{type:'paragraph' as const,text:'Re: {matter.reference} - {client.name}'},{type:'paragraph' as const,text:'{input.body}'},{type:'paragraph' as const,text:'{signatory.name}\n{date.today}'}] };
export const demonstrationPleading = { header: '{firm.name}', footer: 'SYNTHETIC EXAMPLE - REQUIRES PROFESSIONAL REVIEW', blocks: [{type:'heading' as const,text:'DEMONSTRATION PLEADING'},{type:'paragraph' as const,text:'Matter: {matter.reference}\nClient: {client.name}'},{type:'heading' as const,text:'{input.subject}'},{type:'paragraph' as const,text:'{input.body}'},{type:'table' as const,text:'',rows:[['Item','Description'],['1','Synthetic demonstration only']]},{type:'paragraph' as const,text:'Prepared by {signatory.name} on {date.today}'}] };
