const test=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
require('reflect-metadata');
const {PrismaService}=require('../dist/platform/prisma/prisma.service');
const {AuditService}=require('../dist/platform/audit/audit.service');
const {SiteContentService}=require('../dist/modules/website/site-content.service');
const {WebsitePublishingService}=require('../dist/modules/website/website-publishing.service');
const {WebsiteAdminService}=require('../dist/modules/website/website-admin.service');
const {WebsiteLeadsService}=require('../dist/modules/website/website-leads.service');
const {IntakeService}=require('../dist/modules/intake/intake.service');
const {NumberingService}=require('../dist/modules/numbering/numbering.service');
const {CalendarService}=require('../dist/modules/calendar/calendar.service');
const {RedisService}=require('../dist/platform/redis/redis.service');const {QueueService}=require('../dist/platform/queue/queue.service');
const {processWebsitePublish}=require('../../worker/dist/processors/website-publish.processor');
const {PermissionsGuard}=require('../dist/platform/auth/permissions.guard');const {Reflector}=require('@nestjs/core');
const {WebsiteAdminController}=require('../dist/modules/website/website-admin.controller');
const enabled=process.env.RUN_WEBSITE_DATABASE_TESTS==='1';
test('public platform: persistent snapshots, real artifacts, rollback and idempotent intake', {skip:!enabled,timeout:180000},async()=>{
 assert.equal(new URL(process.env.DATABASE_URL).pathname,'/kka_public_local','Only run against the isolated local database');
 const prisma=new PrismaService();const db=prisma.client;const audit=new AuditService(prisma);const redis=new RedisService();const queue=new QueueService(redis);const content=new SiteContentService(prisma);const publishing=new WebsitePublishingService(prisma,queue,audit,content);const cms=new WebsiteAdminService(prisma,audit);const numbering=new NumberingService(prisma);const intake=new IntakeService(prisma,audit,numbering,null,null);const calendar=new CalendarService(prisma,audit,queue);const leads=new WebsiteLeadsService(prisma,numbering,intake,calendar,audit,content);
 try{
 const admin=await db.user.findFirst({where:{firmId:process.env.PUBLIC_BRANDING_FIRM_ID}});const user={...admin,permissions:['website.edit','website.review','website.publish'],roleKeys:[]};
 const publish=async()=>{const r=await publishing.publish(user);await processWebsitePublish({data:{firmId:user.firmId,releaseId:r.id}},db);return r;};
 const first=await publish();const initial=await content.snapshot();assert.ok(initial.pages.find(p=>p.slug==='home').blocks.length);
 const release=await db.websitePublishRelease.findUnique({where:{id:first.id}});assert.ok(release.manifest.artifact.files['index.html']);assert.ok(release.manifest.artifact.files['sitemap.xml']);
 const home=await cms.page(user,initial.pages.find(p=>p.slug==='home').id);const marker='Draft-only '+randomUUID();
 const draft=await cms.savePage(user,{...home,status:'DRAFT',description:marker});
 assert.notEqual((await content.page('home')).description,marker,'Draft save cannot change public content');
 const second=await publish();assert.notEqual((await content.page('home')).description,marker,'Unapproved draft survives unrelated release');
 await assert.rejects(()=>cms.savePage(user,{...home,status:'DRAFT'}),/changed in another session/);
 await assert.rejects(()=>cms.savePage({...user,permissions:['website.edit']},{...draft,status:'APPROVED'}),/Review permission/);
 await cms.savePage(user,{...draft,status:'APPROVED'});
 const frozen=await publishing.publish(user);await db.websitePage.update({where:{id:home.id},data:{description:'Later unpublished edit',status:'DRAFT'}});
 await processWebsitePublish({data:{firmId:user.firmId,releaseId:frozen.id}},db);assert.equal((await content.page('home')).description,marker,'Release must build the requested revision');
 const rollback=await publishing.rollback(user,first.version);await processWebsitePublish({data:{firmId:user.firmId,releaseId:rollback.id}},db);assert.deepEqual((await content.snapshot()).pages,initial.pages);
 assert.equal((await cms.page(user,home.id)).description,'Later unpublished edit','Rollback preserves drafts');
 const {readFile}=require('node:fs/promises');const path=require('node:path');const html=await readFile(path.join(process.env.WEBSITE_RELEASE_ROOT,rollback.id,'index.html'),'utf8');assert.match(html,/<h1/);assert.match(html,/A LAW FIRM THAT/);assert.match(html,/site-snapshot/);
 const input={name:'Local Acceptance Enquiry',phone:'0712345678',email:'acceptance@example.test',message:'Local integration verification enquiry.',consent:true,idempotencyKey:randomUUID()};
 const [a,b]=await Promise.all([leads.createPublic(input,{}),leads.createPublic(input,{})]);assert.equal(a.reference,b.reference);
 const lead=await db.websiteLead.findUnique({where:{reference:a.reference}});assert.equal(await db.websiteFormSubmission.count({where:{leadId:lead.id}}),1);
 await assert.rejects(()=>leads.createPublic({...input,message:'Changed information'},{}),/different information/);
 await assert.rejects(()=>leads.get({...user,firmId:'another-firm'},lead.id),/not found/);
 await assert.rejects(()=>leads.startIntake(user,lead.id),/Qualify/);
 const appt={assignedUserId:user.id,startsAt:'2026-10-01T08:00:00Z',endsAt:'2026-10-01T09:00:00Z'};
 const [one,two]=await Promise.all([leads.appointment(user,lead.id,appt),leads.appointment(user,lead.id,appt)]);assert.equal(one.appointment.id,two.appointment.id);assert.equal(one.calendarEvent.id,two.calendarEvent.id);
 await leads.update(user,lead.id,{status:'CONSULTED'});await leads.update(user,lead.id,{status:'QUALIFIED'});
 const [i,j]=await Promise.all([leads.startIntake(user,lead.id),leads.startIntake(user,lead.id)]);assert.equal(i.id,j.id);assert.match(i.intakeNumber,/KKA\/IN\//);
 await assert.rejects(()=>leads.update(user,lead.id,{status:'CONVERTED'}),/converted formal intake/);
 const guard=new PermissionsGuard(new Reflector());assert.throws(()=>guard.canActivate({getHandler:()=>WebsiteAdminController.prototype.savePage,getClass:()=>WebsiteAdminController,switchToHttp:()=>({getRequest:()=>({authUser:{permissions:[]}})})}),/Missing permissions/);
 console.log('Verified real HTML release, isolated drafts, frozen capture, full rollback, request replay, cross-firm rejection, calendar and intake concurrency.');
 }finally{await queue.onModuleDestroy();await redis.onModuleDestroy();await prisma.onModuleDestroy();}
});
