import { apiClient } from './api/client';

const root='/website/admin';
export const websiteApi={
 dashboard:()=>apiClient.get<any>(`${root}/dashboard`),
 settings:()=>apiClient.get<any>(`${root}/settings`),
 saveSettings:(body:any)=>apiClient.put<any>(`${root}/settings`,body),
 pages:()=>apiClient.get<any[]>(`${root}/pages`),
 page:(id:string)=>apiClient.get<any>(`${root}/pages/${id}`),
 savePage:(body:any)=>body.id?apiClient.put<any>(`${root}/pages/${body.id}`,body):apiClient.post<any>(`${root}/pages`,body),
 restorePage:(id:string,version:number)=>apiClient.post<any>(`${root}/pages/${id}/restore/${version}`),
 deletePage:(id:string)=>apiClient.delete(`${root}/pages/${id}`),
 profiles:()=>apiClient.get<any[]>(`${root}/profiles`),
 saveProfile:(body:any)=>body.id?apiClient.put<any>(`${root}/profiles/${body.id}`,body):apiClient.post<any>(`${root}/profiles`,body),
 deleteProfile:(id:string)=>apiClient.delete(`${root}/profiles/${id}`),
 practiceAreas:()=>apiClient.get<any[]>(`${root}/practice-areas`),
 savePracticeArea:(body:any)=>body.id?apiClient.put<any>(`${root}/practice-areas/${body.id}`,body):apiClient.post<any>(`${root}/practice-areas`,body),
 deletePracticeArea:(id:string)=>apiClient.delete(`${root}/practice-areas/${id}`),
 publications:()=>apiClient.get<any[]>(`${root}/publications`),
 publication:(id:string)=>apiClient.get<any>(`${root}/publications/${id}`),
 savePublication:(body:any)=>body.id?apiClient.put<any>(`${root}/publications/${body.id}`,body):apiClient.post<any>(`${root}/publications`,body),
 restorePublication:(id:string,version:number)=>apiClient.post<any>(`${root}/publications/${id}/restore/${version}`),
 deletePublication:(id:string)=>apiClient.delete(`${root}/publications/${id}`),
 testimonials:()=>apiClient.get<any[]>(`${root}/testimonials`),
 saveTestimonial:(body:any)=>body.id?apiClient.put<any>(`${root}/testimonials/${body.id}`,body):apiClient.post<any>(`${root}/testimonials`,body),
 deleteTestimonial:(id:string)=>apiClient.delete(`${root}/testimonials/${id}`),
 metrics:()=>apiClient.get<any[]>(`${root}/metrics`),
 saveMetric:(body:any)=>body.id?apiClient.put<any>(`${root}/metrics/${body.id}`,body):apiClient.post<any>(`${root}/metrics`,body),
 deleteMetric:(id:string)=>apiClient.delete(`${root}/metrics/${id}`),
 forms:()=>apiClient.get<any[]>(`${root}/forms`),
 saveForm:(body:any)=>body.id?apiClient.put<any>(`${root}/forms/${body.id}`,body):apiClient.post<any>(`${root}/forms`,body),
 deleteForm:(id:string)=>apiClient.delete(`${root}/forms/${id}`),
 media:(q?:string)=>apiClient.get<any[]>(`${root}/media`,{params:q?{q}:undefined}),
 uploadMedia:(form:FormData)=>apiClient.upload<any>(`${root}/media`,form),
 updateMedia:(id:string,body:any)=>apiClient.patch<any>(`${root}/media/${id}`,body),
 deleteMedia:(id:string)=>apiClient.delete(`${root}/media/${id}`),
 leads:(query:Record<string,string|undefined>={})=>apiClient.get<any[]>(`${root}/leads`,{params:query}),
 lead:(id:string)=>apiClient.get<any>(`${root}/leads/${id}`),
 leadAnalytics:(days=30)=>apiClient.get<any>(`${root}/leads/analytics`,{params:{days}}),
 updateLead:(id:string,body:any)=>apiClient.patch<any>(`${root}/leads/${id}`,body),
 assignLead:(id:string,body:any)=>apiClient.post<any>(`${root}/leads/${id}/assign`,body),
 contactLead:(id:string,body:any)=>apiClient.post<any>(`${root}/leads/${id}/contact-attempts`,body),
 appointment:(id:string,body:any)=>apiClient.post<any>(`${root}/leads/${id}/appointments`,body),
 startIntake:(id:string)=>apiClient.post<any>(`${root}/leads/${id}/start-intake`),
 releases:()=>apiClient.get<any[]>(`${root}/publishing/releases`),
 publish:()=>apiClient.post<any>(`${root}/publishing/publish`),
 rollback:(version:number)=>apiClient.post<any>(`${root}/publishing/rollback/${version}`),
};
